let img = document.querySelector('#img')
	let titulo = document.querySelector('#title')
	let paragraph = document.querySelector('#paragraph')
	let link = document.querySelector('#link')
	let autor = document.querySelector('#autor')
	let data = document.querySelector('#data')